<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@include file="../../commons/commons.jspf"%>
<!DOCTYPE HTML>
<html>
<head>
	<meta charset="utf-8">
<link rel="icon" href="https://static.jianshukeji.com/highcharts/images/favicon.ico">
<meta name="viewport" content="width=device-width, initial-scale=1">	<script src="https://img.hcharts.cn/highcharts/highcharts.js"></script>
	<script src="https://img.hcharts.cn/highcharts/modules/exporting.js"></script>
	<script src="https://img.hcharts.cn/highcharts-plugins/highcharts-zh_CN.js"></script>
<style>
	div.container{
		float:left;	
	}
</style>
</head>
<body>
<!--
*************************************************************************
   Generated by HCODE at 2017-08-20 23:08:54
   From: https://code.hcharts.cn/temp/R4ClAv/1
*************************************************************************
 -->
<div class="container" id="container1" style="min-width:400px;width:600px;height:400px;"></div>
<div class="container" style="height:400px"><div id="container2" style="min-width:400px;width:300px;height:300px"></div></div>
<div class="container" id="container3" style="min-width:400px;width:600px;height:400px;"></div>

	<script>
	/**
  * Highcharts 在 4.2.0 开始已经不依赖 jQuery 了，直接用其构造函数既可创建图表
 **/
    $.getJSON("${path}/customer/countAge.action",function (result) {
        console.log(result)
        $('#container1').highcharts({
            title: {
                text: '不同年龄客户分布',
                x: -20
            },
            subtitle: {
                text: '数据来源: hxj.com',
                x: -20
            },
            xAxis: {
                categories: ['18～30', '31～40', '41～50', '51～60', '61～70', '其他']
            },
            yAxis: {
                title: {
                    text: '人数'
                },
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }]
            },
            tooltip: {
                valueSuffix: '人'
            },
            legend: {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'middle',
                borderWidth: 0
            },
            series: [{
                name:'客户人数',
                data: [result['18～30'], result['31～40'], result['41～50'], result['51～60'], result['61～70'],result['其他']]
            }]
        });
    })

</script>


	<script>
        $.getJSON("${path}/customer/countGender.action",function (result) {
            $('#container2').highcharts({
                title: {
                    text: '客户性别占比'
                },
                tooltip: {
                    headerFormat: '{series.name}<br>',
                    pointFormat: '{point.name}: <b>{point.percentage:.1f}%</b>'
                },
                plotOptions: {
                    pie: {
                        allowPointSelect: true,
                        cursor: 'pointer',
                        dataLabels: {
                            enabled: true,
                            format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                            style: {
                                color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                            }
                        }
                    }
                },
                series: [{
                    type: 'pie',
                    name: '客户性别分布',
                    data: [
                        ['男',   result[0]],
                        {
                            name: '女',
                            y: result[1],
                            sliced: true,
                            selected: true,
                        },
                    ]
                }]
            });
        });
</script>


<script>
$.getJSON("${path}/customer/countProvince.action",function (result) {
    console.log(result)
    $('#container3').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: '客户区域分布'
        },
        subtitle: {
            text: '数据来源: hxj.com'
        },
        xAxis: {
            categories: [
                '陕西省',
                '河南省',
                '安徽省',
                '山西省',
                '青海省',
                '内蒙古省',
                '甘肃省',
                '四川省',
                '重庆市',
                '山东省',
                '云南省',
                '其他省'
            ],
            crosshair: true
        },
        yAxis: {
            min: 0,
            title: {
                text: '人数(人)'
            }
        },
        tooltip: {
            headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
            '<td style="padding:0"><b>{point.y}人</b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
        series: [{
            name:'客户人数',
            data: [result['陕西省'], result['河南省'], result['安徽省'], result['山西省'],
                result['青海省'], result['内蒙古省'],result['甘肃省'], result['四川省'],
                result['重庆省'], result['山东省'], result['云南省'], result['其他']]
        }]
    });
})

</script>
</body>
</html>
