<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@include file="../../commons/commons.jspf"%>
<!DOCTYPE HTML>
<html>
<head>
	<meta charset="utf-8">
<link rel="icon" href="https://static.jianshukeji.com/highcharts/images/favicon.ico">
<meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://img.hcharts.cn/jquery/jquery-1.8.3.min.js"></script>
	<script src="https://img.hcharts.cn/highcharts/highcharts.js"></script>
	<script src="https://img.hcharts.cn/highcharts/modules/exporting.js"></script>
	<script src="https://img.hcharts.cn/highcharts-plugins/highcharts-zh_CN.js"></script>
</head>
<body>
<!--
*************************************************************************
   Generated by HCODE at 2017-08-23 17:20:07
   From: https://code.hcharts.cn/temp/OINlac
*************************************************************************
 -->
<div id="container1" style="min-width:400px;height:400px"></div>

<script>
    $(function () {
        $.getJSON("${path}/car/countCarByAll.action",function (result) {
            var cnameList = [];
            var attitude = [];
            var exterior = [];
            var trim = [];
            var space = [];
            for(var i = 0;i<result.length;i++){
                var car = result[i]
                cnameList.push(car.cName);
                attitude.push(car.attitude)
                exterior.push(car.exterior)
                trim.push(car.trim)
                space.push(car.space)
            }
        $('#container1').highcharts({
            chart: {
                type: 'column'
            },
            title: {
                text: '汽车品牌评价汇总'
            },
            subtitle: {
                text: '数据来源: hxj.com'
            },
            xAxis: {
                categories:cnameList,
                crosshair: true
            },
            yAxis: {
                min: 0,
                title: {
                    text: '客户评价(分)'
                }
            },
            tooltip: {
                headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                '<td style="padding:0"><b>{point.y:.1f}分</b></td></tr>',
                footerFormat: '</table>',
                shared: true,
                useHTML: true
            },
            plotOptions: {
                column: {
                    pointPadding: 0.2,
                    borderWidth: 0
                }
            },
            series: [{
                name: '服务态度',
                data: attitude
            }, {
                name: '外观设计',
                data: exterior
            }, {
                name: '内饰配置',
                data: trim
            }, {
                name: '空间布局',
                data: space
            }]
        });
    });
    })
</script>
	<div id="container2" style="min-width:400px;height:400px"></div>

	<script>
	$(function () {
	    $.getJSON("${path}/car/countCarByEvery.action",{what:'attitude'},function (result) {
	        var datas = [];
	        for(var i = 0;i<result.length;i++){
	            var data = [result[i].cName,result[i].attitude];
                datas.push(data);
            }
            $('#container2').highcharts({
                chart: {
                    type: 'column'
                },
                title: {
                    text: '汽车品牌服务态度评分排行'
                },
                xAxis: {
                    type: 'category',
                    labels: {
                        rotation: -45,
                        style: {
                            fontSize: '13px',
                            fontFamily: 'Verdana, sans-serif'
                        }
                    }
                },
                yAxis: {
                    min: 0,
                    title: {
                        text: '客户评价(分)'
                    }
                },
                legend: {
                    enabled: false
                },
                tooltip: {
                    pointFormat: '客户评分: <b>{point.y:.1f} 分</b>'
                },
                series: [{
                    name: '总人口',
                    data: datas,
                    dataLabels: {
                        enabled: true,
                        rotation: -90,
                        color: '#FFFFFF',
                        align: 'right',
                        format: '{point.y:.1f}', // one decimal
                        y: 10, // 10 pixels down from the top
                        style: {
                            fontSize: '13px',
                            fontFamily: 'Verdana, sans-serif'
                        }
                    }
                }]
            });
        });
    })
</script>

<div id="container3" style="min-width:400px;height:400px"></div>

<script>
    $(function () {
        $.getJSON("${path}/car/countCarByEvery.action",{what:'exterior'},function (result) {
            var datas = [];
            for(var i = 0;i<result.length;i++){
                var data = [result[i].cName,result[i].exterior];
                datas.push(data);
            }
            $('#container3').highcharts({
                chart: {
                    type: 'column'
                },
                title: {
                    text: '汽车品牌外观设计评分排行'
                },
                xAxis: {
                    type: 'category',
                    labels: {
                        rotation: -45,
                        style: {
                            fontSize: '13px',
                            fontFamily: 'Verdana, sans-serif'
                        }
                    }
                },
                yAxis: {
                    min: 0,
                    title: {
                        text: '客户评价(分)'
                    }
                },
                legend: {
                    enabled: false
                },
                tooltip: {
                    pointFormat: '客户评分: <b>{point.y:.1f} 分</b>'
                },
                series: [{
                    name: '总人口',
                    data: datas,
                    dataLabels: {
                        enabled: true,
                        rotation: -90,
                        color: '#FFFFFF',
                        align: 'right',
                        format: '{point.y:.1f}', // one decimal
                        y: 10, // 10 pixels down from the top
                        style: {
                            fontSize: '13px',
                            fontFamily: 'Verdana, sans-serif'
                        }
                    }
                }]
            });
        });
    })
</script>
<div id="container4" style="min-width:400px;height:400px"></div>

<script>
    $(function () {
        $.getJSON("${path}/car/countCarByEvery.action",{what:'trim'},function (result) {
            var datas = [];
            for(var i = 0;i<result.length;i++){
                var data = [result[i].cName,result[i].trim];
                datas.push(data);
            }
            $('#container4').highcharts({
                chart: {
                    type: 'column'
                },
                title: {
                    text: '汽车品牌内饰配置评分排行'
                },
                xAxis: {
                    type: 'category',
                    labels: {
                        rotation: -45,
                        style: {
                            fontSize: '13px',
                            fontFamily: 'Verdana, sans-serif'
                        }
                    }
                },
                yAxis: {
                    min: 0,
                    title: {
                        text: '客户评价(分)'
                    }
                },
                legend: {
                    enabled: false
                },
                tooltip: {
                    pointFormat: '客户评分: <b>{point.y:.1f} 分</b>'
                },
                series: [{
                    name: '总人口',
                    data: datas,
                    dataLabels: {
                        enabled: true,
                        rotation: -90,
                        color: '#FFFFFF',
                        align: 'right',
                        format: '{point.y:.1f}', // one decimal
                        y: 10, // 10 pixels down from the top
                        style: {
                            fontSize: '13px',
                            fontFamily: 'Verdana, sans-serif'
                        }
                    }
                }]
            });
        });
    })
</script>
<div id="container5" style="min-width:400px;height:400px"></div>

<script>
    $(function () {
        $.getJSON("${path}/car/countCarByEvery.action",{what:'space'},function (result) {
            var datas = [];
            for(var i = 0;i<result.length;i++){
                var data = [result[i].cName,result[i].space];
                datas.push(data);
            }
            $('#container5').highcharts({
                chart: {
                    type: 'column'
                },
                title: {
                    text: '汽车品牌空间布局评分排行'
                },
                xAxis: {
                    type: 'category',
                    labels: {
                        rotation: -45,
                        style: {
                            fontSize: '13px',
                            fontFamily: 'Verdana, sans-serif'
                        }
                    }
                },
                yAxis: {
                    min: 0,
                    title: {
                        text: '客户评价(分)'
                    }
                },
                legend: {
                    enabled: false
                },
                tooltip: {
                    pointFormat: '客户评分: <b>{point.y:.1f} 分</b>'
                },
                series: [{
                    name: '总人口',
                    data: datas,
                    dataLabels: {
                        enabled: true,
                        rotation: -90,
                        color: '#FFFFFF',
                        align: 'right',
                        format: '{point.y:.1f}', // one decimal
                        y: 10, // 10 pixels down from the top
                        style: {
                            fontSize: '13px',
                            fontFamily: 'Verdana, sans-serif'
                        }
                    }
                }]
            });
        });
    })
</script>
</body>
</html>